In [18]:
import numpy as np

#definindo vetor Q:

q1, q2, q3, q4, q5, q6 = 0.6, 0.4, 0.1, 0, 0.3, 0.2

Q = np.array([q1, q2, q3, q4, q5, q6])

# criando os índices de linhas (row):
row_ind = np.array([0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5])

# criando os índices da coluna (columns)
col_ind = np.array([0, 1, 2, 2, 3, 0, 4, 5, 1, 4, 3])

# criando os índices dos dados (data):
data = np.array([1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1], dtype=float)

In [19]:
import matplotlib.pyplot as plt
from scipy import sparse
from scipy.sparse import csr_matrix 

A_coord = sparse.coo_matrix((data, (row_ind, col_ind)), dtype= float)

print(A_coord)

<COOrdinate sparse matrix of dtype 'float64'
	with 11 stored elements and shape (6, 6)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (2, 3)	-1.0
  (3, 0)	1.0
  (3, 4)	1.0
  (3, 5)	-1.0
  (4, 1)	-1.0
  (4, 4)	1.0
  (5, 3)	1.0


In [20]:
A = sparse.coo_matrix((data, (row_ind, col_ind)), dtype= float).toarray()
print(A)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.]
 [ 1.  0.  0.  0.  1. -1.]
 [ 0. -1.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.]]


In [21]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  1. -1.  0.  1. -1.]
 [ 1.  1. -1. -1.  1. -1.]]


In [22]:
x = A_inv.dot(Q)

Q2 = x[0]
Q4= x[1]
Q5 = x[2]
Q7 = x[3]
Q9 = x[4]
Q10 = x[5]

def line():
    print('-'*50)

line()
print('     Valores das vazões')
line()
print('O resultado de Q2 = {:.2f}'.format(Q2), 'm³/min')
print('O resultado de Q4 = {:.2f}'.format(Q4), 'm³/min')
print('O resultado de Q5 = {:.2f}'.format(Q5), 'm³/min')
print('O resultado de Q7 = {:.2f}'.format(Q7), 'm³/min')
print('O resultado de Q9 = {:.2f}'.format(Q9), 'm³/min')
print('O resultado de Q10 = {:.2f}'.format(Q10), 'm³/min')
line()

--------------------------------------------------
     Valores das vazões
--------------------------------------------------
O resultado de Q2 = 0.60 m³/min
O resultado de Q4 = 0.10 m³/min
O resultado de Q5 = 0.30 m³/min
O resultado de Q7 = 0.20 m³/min
O resultado de Q9 = 0.40 m³/min
O resultado de Q10 = 1.00 m³/min
--------------------------------------------------


In [25]:
#Conferindo os resultados 

Q2 = 0.6
Q5 = 0.1 + 0.2
Q7 = 0.2
Q4 = 0.4 - Q5
Q9 = 0.3 + Q4 
Q10 = Q9 + Q2

def line():
    print('-'*50)

line()
print('Conferindo valores das vazões')
line()

print('O resultado de Q2 = {:.2f}'.format(Q2), 'm³/min')
print('O resultado de Q4 = {:.2f}'.format(Q4), 'm³/min')
print('O resultado de Q5 = {:.2f}'.format(Q5), 'm³/min')
print('O resultado de Q7 = {:.2f}'.format(Q7), 'm³/min')
print('O resultado de Q9 = {:.2f}'.format(Q9), 'm³/min')
print('O resultado de Q10 = {:.2f}'.format(Q10), 'm³/min')
line()

--------------------------------------------------
Conferindo valores das vazões
--------------------------------------------------
O resultado de Q2 = 0.60 m³/min
O resultado de Q4 = 0.10 m³/min
O resultado de Q5 = 0.30 m³/min
O resultado de Q7 = 0.20 m³/min
O resultado de Q9 = 0.40 m³/min
O resultado de Q10 = 1.00 m³/min
--------------------------------------------------
