In [1]:
import numpy as np

#Definindo variaveis 

a11, a12 = 0.82, 0
a21, a22 = 0, 0.20

A = np.array([[a11, a12], [a21, a22]])
A

array([[0.82, 0.  ],
       [0.  , 0.2 ]])

In [2]:
b1, b2 = 60, 40

s = np.array([b1, b2])

In [3]:
#Método algébrico 
#Fazendo determinante 

det_A = (a11*a22) - (a12*a21) 
det_A

0.164

In [4]:
#Determinando a matriz cofatora

i = 1
j = 1

c11 = (-1)**(i+j) * a22
c11

0.2

In [6]:
i = 1
j = 2

c12 = (-1)**(i+j) * a21
c12

0

In [7]:
i = 2
j = 1

c21 = (-1)**(i+j) * a12
c21

0

In [8]:
i = 2
j = 2

c22 = (-1)**(i+j) * a11
c22

0.82

In [9]:
C = np.array([[c11, c12], [c21, c22]])
C

array([[0.2 , 0.  ],
       [0.  , 0.82]])

In [10]:
adj_A = C.T
A_inv = adj_A / det_A
A_inv


array([[1.2195122, 0.       ],
       [0.       , 5.       ]])

In [11]:
X = np.dot(A_inv, s)
np.set_printoptions(precision=3, suppress=True)

print('Valor de x1 = {:.3f}'.format(X[0]) )
print('Valor de x2 = {:.3f}'.format(X[1]))

Valor de x1 = 73.171
Valor de x2 = 200.000


In [12]:
#Usando bibliotecas, temos: 

inv_A = np.linalg.inv(A)
inv_A

array([[1.22, 0.  ],
       [0.  , 5.  ]])

In [13]:
x = np.dot(inv_A, s)
np.set_printoptions(precision=3, suppress=True)

print('Valor de x1 = {:.3f}'.format(X[0]))
print('Valor de x2 = {:.3f}'.format(X[1]))

Valor de x1 = 73.171
Valor de x2 = 200.000
