## <center>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC<center> <center>DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO - DEC </center>
#### <center>CURSO DE ENGENHARIA QUÍMICA</center>

**CET 1012** Modelagem, Simulação e Otimização de Processos Químicos.

**Professor**: Prof. Dr E.R.Edwards

**Tema:** Métodos Matriciais em Cálculos de Engenharia.

**Assunto**Manipulação de matrizes para cálculo de Engenharia

#### Definição de Matriz

Matriz é um conjunto de dados divididos por linhas e colunas e possui uma estrutura matemática disposta em tabelas com operações de adição, subtração e multiplicação bem definidas. Existem casos especiais que são classificados de acordo com a característica da matriz. A matriz abaixo mostra a disposição

$$ A_{i,j} = [a_{i,j}] $$

De tal forma que:

\begin{equation}	
	A = 
	\begin{bmatrix}
		a_{11} &a_{12}   & \ldots &  a_{1n} \\
		a_{21} &a_{22}   & \ldots &  a_{2n} \\
        \vdots &\vdots   & \ddots &  \vdots \\
        a_{m1} &a_{m2}   & \ldots &  a_{mn}   \\ \nonumber 
        \end{bmatrix}
    \end{equation}

Sendo $i$ o índice das linhas e $j$ o índice das colunas. A diagonal da matriz $A$ são inteiros $a_{ij}$ em que $i=j$


Agora vamos identificar os valores numéricos armazenados nas célunas de uma Matriz mostrada abaixo.

\begin{equation}
    \begin{bmatrix}
    -3 & 2 & 4 \\
    5 & 6 & 3 \\
    \end{bmatrix}
\end{equation}

É representado pela lista: [[2, -3, 4], [0, 7, 5]]
#### Vamos analisar a Matriz abaixo:

# A matriz é escrita como:


In [2]:
Matriz= [[-3, 2, 4],
         [5, 6, 3]]

In [3]:
# Vamos identificar a primeira linha.
Mat00 = Matriz[0][0]
Mat01 = Matriz[0][1]
Mat02 = Matriz[0][2]

#print(f"Mat00 = {Mat00}, Mat01 = {Mat01}, Mat02 = {Mat02}")
print('Mat00 = {}, Mat01 = {}, Mat02 = {}'.format(Mat00, Mat01, Mat02))

Mat00 = -3, Mat01 = 2, Mat02 = 4


In [4]:
# Vamos identificar a segunda linha.
Mat10 = Matriz[1][0]
Mat11 = Matriz[1][1]
Mat12 = Matriz[1][2]

print('Mat10 = {}, Mat11 = {}, Mat12 = {}'.format(Mat10, Mat11, Mat12))


Mat10 = 5, Mat11 = 6, Mat12 = 3


#### 1 - Soma de matrizes e resolução computacional

Seja a matriz $A$ e $B$ dada por:


\begin{equation}	
A = 
	\begin{bmatrix}
		a_{11} & a_{12}   & \ldots &  a_{1n} \\
		a_{21} & a_{22}   & \ldots &  a_{2n} \\
        \vdots & \vdots   & \ddots &  \vdots \\
        a_{m1} & a_{m2}   & \ldots &  a_{mn}   \\ \nonumber 
        \end{bmatrix}
    \
    \
  	B = 
	\begin{bmatrix}
		b_{11} & a_{12}  & \ldots &  b_{1n} \\
		b_{21} &a_{22}   & \ldots &  b_{2n} \\
        \vdots &\vdots   & \ddots &  \vdots \\
        b_{m1} &a_{m2}   & \ldots &  b_{mn}   \\ \nonumber 
        \end{bmatrix}
\end{equation}
A soma de duas matrizes é dada por:

\begin{equation}	
C = 
	\begin{bmatrix}
		a_{11} + b_{11}  &  a_{12} + a_{12}   & \ldots &  a_{1n} + b_{1n}  \\
		a_{21} + b_{21}  &  a_{22} + a_{22}   & \ldots &  a_{2n} + b_{2n}  \\
                 \vdots  &           \vdots   & \ddots &         \vdots    \\
        a_{m1} + b_{m1}  &  a_{m2} + a_{m2}   & \ldots &  a_{mn} + b_{mn}  \\ \nonumber 
        \end{bmatrix}
\end{equation}


#### **Exercício**

calcule a matriz $C$  sabendo-se que é a soma da Matriz  $A$ e $B$.

\begin{equation}	
	A = 
	\begin{bmatrix}
		1 & 2 & 3 \\
       	4 & 5 & 6  \nonumber \\ 
        \end{bmatrix}
        \
        B = 
	\begin{bmatrix}
		2 & 1 & 4 \\
       	1 & 1 & 2  \nonumber \\ 
        \end{bmatrix}
    \end{equation}
    
**Resposta:**
\begin{equation}	
	C = A+B =
	\begin{bmatrix}
		3 & 3 & 7 \\
       	5 & 6 & 8  \nonumber \\ 
        \end{bmatrix}
\end{equation}


In [6]:
#matriz A 
a11, a12, a13 = 1, 2, 3
a21, a22, a23 = 4, 5, 6
#matriz B
b11, b12, b13 = 2, 1, 4
b21, b22, b23 = 1, 1, 2

#Soma das matrizes A+B
c = [[a11+b11, a12+b12, a13+b13], [a21+b21, a22+b22, a23+b23]]
print('A matriz C = {}'.format(c))

A matriz C = [[3, 3, 7], [5, 6, 8]]


#### 1.1 - Vamos fazer a soma das matrizes usando a biblioteca Numpy.


In [7]:
# Soma de matrizes usando a biblioteca Numpy.
import numpy as np

# Matriz A.
A1 = np.array([[1, 2, 3],
               [4, 5, 6]])

# Matriz B.
B1 = np.array([[2, 1, 4],
               [1, 1, 2]])

C1 = A1+B1
C1


array([[3, 3, 7],
       [5, 6, 8]])

In [8]:
# ou podemos resolver usando add de adição.

C2 = np.add(A1, B1)
C2


array([[3, 3, 7],
       [5, 6, 8]])

#### 2 - Subtração de matrizes e resolução computacional

A diferença de duas matrizes $A-B$ de ordem $(mxn)$ é uma matriz $C$ tal que:

$$ c_{ij} = a_{ij} - b_{ij}$$


Seja a matriz $A$ e $B$ dada por:

\begin{equation}	
A = 
	\begin{bmatrix}
		a_{11} & a_{12}   & \ldots &  a_{1n} \\
		a_{21} & a_{22}   & \ldots &  a_{2n} \\
        \vdots & \vdots   & \ddots &  \vdots \\
        a_{m1} & a_{m2}   & \ldots &  a_{mn}   \\ \nonumber 
        \end{bmatrix}
    \
    \
  	B = 
	\begin{bmatrix}
		b_{11} &  b_{12}  & \ldots &   b_{1n} \\
		b_{21} &  b_{22}   & \ldots &  b_{2n} \\
        \vdots &  \vdots   & \ddots &  \vdots \\
        b_{m1} &  b_{m2}   & \ldots &  b_{mn}   \\ \nonumber 
        \end{bmatrix}
\end{equation}


A subtração de duas matrizes é dada por:

\begin{equation}	
C = 
	\begin{bmatrix}
		a_{11} - b_{11}  &  a_{12} - b_{12}   & \ldots &  a_{1n} - b_{1n}  \\
		a_{21} - b_{21}  &  a_{22} - b_{22}   & \ldots &  a_{2n} - b_{2n}  \\
                 \vdots  &           \vdots   & \ddots &         \vdots    \\
        a_{m1} - b_{m1}  &  a_{m2} - b_{m2}   & \ldots &  a_{mn} - b_{mn}  \\ \nonumber 
        \end{bmatrix}
\end{equation}



#### **Exercício**

Calcule a matriz $C$  sabendo-se que é a subtração da Matriz  $A$ e $B$.

\begin{equation}	
	A = 
	\begin{bmatrix}
		2 & 3 & 1 \\
       	3 & 4 & 5  \nonumber \\ 
        \end{bmatrix}
        \
        B = 
	\begin{bmatrix}
		3 & 2 & 1 \\
       	2 & 1 & 3  \nonumber \\ 
        \end{bmatrix}
    \end{equation}
    
**Resposta:**
\begin{equation}	
	C = A-B =
	\begin{bmatrix}
		-1 & 1 & 0 \\
       	1 & 3 & 2  \nonumber \\ 
        \end{bmatrix}
\end{equation}


In [10]:
A2 = np.array([[2,3,1],[3,4,5]])
B2 = np.array([[3,2,1],[2,1,3]])

C3 = np.subtract(A2, B2)
C3

array([[-1,  1,  0],
       [ 1,  3,  2]])

#### 3 - Multiplicação de matrizes e resolução computacional


A multiplicação de duas matrizes são dadas por:

$$ C_{i,j} = \sum_k A_{i,k}B_{k,j} $$

Seja a matriz $A$ e  $B$:

\begin{equation}	
	A = 
	\begin{bmatrix}
		a_{11} &  a_{12}  \\
		a_{21} &  a_{22} \\
        a_{31} &  a_{32}\nonumber \\ 
        \end{bmatrix}_{(3x2)}
    \
    \
    B = 
	\begin{bmatrix}
		b_{11} &  b_{12} \\
		b_{21} &  b_{22}  \nonumber \\ 
	\end{bmatrix}_{(2x2)}
\end{equation}

Podemos fazer a multiplicação das matrizes por:

\begin{equation}
C = A.B = 
\begin{bmatrix}
a_{11}.b_{11} + a_{12}.b_{21}  &  a_{11}.b_{12} + a_{12}.b_{22} \\
a_{21}.b_{11} + a_{22}.b_{21}  &  a_{21}.b_{12} + a_{22}.b_{22} \\
a_{31}.b_{11} + a_{32}.b_{21}  &  a_{31}.b_{12} + a_{32}.b_{22}  \nonumber \\ 
\end{bmatrix}
=
\begin{bmatrix}
		c_{11} &  c_{12} \\
        c_{21} &  c_{22} \\
		c_{31} &  c_{32}  \nonumber \\ 
	\end{bmatrix}
\end{equation}


**Exercício :** Cálcule a multiplicação das matrizes abaixo usando método algébrico e compare com o resultado usando a biblioteca Numpy.


\begin{equation}	
	A = 
	\begin{bmatrix}
		1 &  2  \\
		3 &  4 \\
        5 &  6  \nonumber \\ 
        \end{bmatrix}_{(3x2)}
    \
    \
    \
    B = 
	\begin{bmatrix}
		1 &  3 \\
		2 &  4  \nonumber \\ 
	\end{bmatrix}_{(2x2)}
\end{equation}


**Resultado:**

\begin{equation}	
	C= A.B = 
	\begin{bmatrix}
		5 & 11  \\
		11 & 25  \\
        17 & 39 \nonumber \\ 
        \end{bmatrix}
    \end{equation}


In [12]:
#método algébrico 
a11, a12 = 1,2
a21, a22 = 3,4
a31, a32 = 5,6

b11, b12 = 1,3
b21, b22 = 2,4

#Multiplicacao de matrizes A*B
c11 = a11*b11 + a12*b21
c12 = a11*b12 + a12*b22
c21 = a21*b11 + a22*b21
c22 = a21*b12 + a22*b22
c31 = a31*b11 + a32*b21 
c32 = a31*b12 + a32*b22

C = [[c11, c12], [c21, c22], [c31, c32]]
C

[[5, 11], [11, 25], [17, 39]]

In [19]:
A3 = np.array([[1, 2],[3, 4],[5, 6]]) 
B3 = np.array([[1, 3],[2, 4]])

C4 = np.dot(A3, B3)
C4

array([[ 5, 11],
       [11, 25],
       [17, 39]])