## <center>UNIVERSIDADE ESTADUAL DE SANTA CRUZ - UESC<center> <center>DEPARTAMENTO DE ENGENHARIAS E COMPUTAÇÃO - DEC </center>
#### <center>CURSO DE ENGENHARIA QUÍMICA</center>

**CET 1012** Modelagem, Simulação e Otimização de Processos Químicos.

**Professor**: Prof. Dr E.R.Edwards

**Tema:** Métodos Matriciais em Cálculos de Engenharia.

**Assunto**Manipulação de matrizes para cálculo de Engenharia.
**negrito**

#### Definição de Matriz

Matriz é um conjunto de dados divididos por linhas e colunas e possui uma estrutura matemática disposta em tabelas com operações de adição, subtração e multiplicação bem definidas. Existem casos especiais que são classificados de acordo com a característica da matriz. A matriz abaixo mostra a disposição

$$ A_{i,j} = [a_{i,j}] $$

De tal forma que:

\begin{equation}
	A =
	\begin{bmatrix}
		a_{11} &a_{12}   & \ldots &  a_{1n} \\
		a_{21} &a_{22}   & \ldots &  a_{2n} \\
        \vdots &\vdots   & \ddots &  \vdots \\
        a_{m1} &a_{m2}   & \ldots &  a_{mn}   \\ \nonumber
        \end{bmatrix}
    \end{equation}

Sendo $i$ o índice das linhas e $j$ o índice das colunas. A diagonal da matriz $A$ são inteiros $a_{ij}$ em que $i=j$

Agora vamos identificar os valores numéricos armazenados nas célunas de uma Matriz mostrada abaixo.

\begin{equation}
    \begin{bmatrix}
    -3 & 2 & 4 \\
    5 & 6 & 3 \\
    \end{bmatrix}
\end{equation}

É representado pela lista: [[2, -3, 4], [0, 7, 5]]
  

#### Vamos analisar a Matriz abaixo:


In [ ]:
# A matriz é escrita como:
Matriz= [[-3, 2, 4],
         [5, 6, 3]]


In [ ]:

# Vamos identificar a primeira linha.
Mat00 = Matriz[0][0]
Mat01 = Matriz[0][1]
Mat02 = Matriz[0][2]

#print(f"Mat00 = {Mat00}, Mat01 = {Mat01}, Mat02 = {Mat02}")
print('Mat00 = {}, Mat01 = {}, Mat02 = {}'.format(Mat00, Mat01, Mat02))


Mat00 = -3, Mat01 = 2, Mat02 = 4


In [ ]:
# Vamos identificar a segunda linha.
Mat10 = Matriz[1][0]
Mat11 = Matriz[1][1]
Mat12 = Matriz[1][2]

print('Mat10 = {}, Mat11 = {}, Mat12 = {}'.format(Mat10, Mat11, Mat12))


Mat10 = 5, Mat11 = 6, Mat12 = 3


#### 1 - Soma de matrizes e resolução computacional

Seja a matriz $A$ e $B$ dada por:


\begin{equation}
A =
	\begin{bmatrix}
		a_{11} & a_{12}   & \ldots &  a_{1n} \\
		a_{21} & a_{22}   & \ldots &  a_{2n} \\
        \vdots & \vdots   & \ddots &  \vdots \\
        a_{m1} & a_{m2}   & \ldots &  a_{mn}   \\ \nonumber
        \end{bmatrix}
    \
    \
  	B =
	\begin{bmatrix}
		b_{11} & a_{12}  & \ldots &  b_{1n} \\
		b_{21} &a_{22}   & \ldots &  b_{2n} \\
        \vdots &\vdots   & \ddots &  \vdots \\
        b_{m1} &a_{m2}   & \ldots &  b_{mn}   \\ \nonumber
        \end{bmatrix}
\end{equation}
A soma de duas matrizes é dada por:

\begin{equation}
C =
	\begin{bmatrix}
		a_{11} + b_{11}  &  a_{12} + a_{12}   & \ldots &  a_{1n} + b_{1n}  \\
		a_{21} + b_{21}  &  a_{22} + a_{22}   & \ldots &  a_{2n} + b_{2n}  \\
                 \vdots  &           \vdots   & \ddots &         \vdots    \\
        a_{m1} + b_{m1}  &  a_{m2} + a_{m2}   & \ldots &  a_{mn} + b_{mn}  \\ \nonumber
        \end{bmatrix}
\end{equation}



#### **Exercício**

calcule a matriz $C$  sabendo-se que é a soma da Matriz  $A$ e $B$.

\begin{equation}
	A =
	\begin{bmatrix}
		1 & 2 & 3 \\
       	4 & 5 & 6  \nonumber \\
        \end{bmatrix}
        \
        B =
	\begin{bmatrix}
		2 & 1 & 4 \\
       	1 & 1 & 2  \nonumber \\
        \end{bmatrix}
    \end{equation}
    
**Resposta:**
\begin{equation}
	C = A+B =
	\begin{bmatrix}
		3 & 3 & 7 \\
       	5 & 6 & 8  \nonumber \\
        \end{bmatrix}
\end{equation}


In [ ]:
# Soma de matrizes pelo método algébrico
#matriz A:
a11, a12, a13 = 1, 2, 3
a21, a22, a23 = 4, 5, 6

#matriz B:
b11, b12, b13 = 2, 1, 4
b21, b22, b23 = 1, 1, 2

#Soma de matrizes

C = [[a11+b11, a12+b12, a13+b13],
     [a21+b21, a22+b22, a23+b23]

]
print('A matriz c = ', (C))

A matriz c =  [[3, 3, 7], [5, 6, 8]]


#### 1.1 - Vamos fazer a soma das matrizes usando a biblioteca Numpy.

In [ ]:
# Soma de matrizes usando a biblioteca Numpy.
import numpy as np

# Matriz A.
A1 = np.array([[1, 2, 3],
               [4, 5, 6]])

# Matriz B.
B1 = np.array([[2, 1, 4],
               [1, 1, 2]
              ])

C1 = A1+B1
C1


array([[3, 3, 7],
       [5, 6, 8]])

In [ ]:
# ou podemos resolver usando add de adição.

C2 = np.add(A1, B1)
C2


array([[3, 3, 7],
       [5, 6, 8]])

#### 2 - Subtração de matrizes e resolução computacional

A diferença de duas matrizes $A-B$ de ordem $(mxn)$ é uma matriz $C$ tal que:

$$ c_{ij} = a_{ij} - b_{ij}$$


#### **Exercício**

Calcule a matriz $C$  sabendo-se que é a subtração da Matriz  $A$ e $B$.

\begin{equation}
	A =
	\begin{bmatrix}
		2 & 3 & 1 \\
       	3 & 4 & 5  \nonumber \\
        \end{bmatrix}
        \
        B =
	\begin{bmatrix}
		3 & 2 & 1 \\
       	2 & 1 & 3  \nonumber \\
        \end{bmatrix}
    \end{equation}
    
**Resposta:**
\begin{equation}
	C = A-B =
	\begin{bmatrix}
		-1 & 1 & 0 \\
       	1 & 3 & 2  \nonumber \\
        \end{bmatrix}
\end{equation}



In [ ]:
#Subtração de matriz
# Soma de matrizes pelo método algébrico
#matriz A:
a11, a12, a13 = 2, 3, 1
a21, a22, a23 = 3, 4, 5

#matriz B:
b11, b12, b13 = 3, 2, 1
b21, b22, b23 = 2, 1, 3

#Soma de matrizes

C = [[a11-b11, a12-b12, a13-b13],
     [a21-b21, a22-b22, a23-b23]

]
print('A matriz c = ', (C))


A matriz c =  [[-1, 1, 0], [1, 3, 2]]


In [ ]:
# Subtração de matrizes usando a biblioteca Numpy.


# Matriz A.
#np é uma biblioteca e array é uma função da minha biblioteca, obs: Toda função necessita de parênteses
A1 = np.array([[2, 3, 1], #O cochete "[]" verde indica início e término da minha matriz. O "[]" marrom, informa as linhas da minha matriz
               [3, 4, 5]])

# Matriz B.
B1 = np.array([[3, 2, 1],
               [2, 1, 3]
              ])

C1 = A1-B1
print('Resultado feito á mão {}'.format(C1))

C2= np.subtract(A1, B1)
print(C2)

Resultado feito á mão [[-1  1  0]
 [ 1  3  2]]
[[-1  1  0]
 [ 1  3  2]]


#### 3 - Multiplicação de matrizes e resolução computacional


A multiplicação de duas matrizes são dadas por:

$$ C_{i,j} = \sum_k A_{i,k}B_{k,j} $$

Seja a matriz $A$ e  $B$:

\begin{equation}
	A =
	\begin{bmatrix}
		a_{11} &  a_{12}  \\
		a_{21} &  a_{22} \\
        a_{31} &  a_{32}\nonumber \\
        \end{bmatrix}_{(3x2)}
    \
    \
    B =
	\begin{bmatrix}
		b_{11} &  b_{12} \\
		b_{21} &  b_{22}  \nonumber \\
	\end{bmatrix}_{(2x2)}
\end{equation}

Podemos fazer a multiplicação das matrizes por:

\begin{equation}
C = A.B =
\begin{bmatrix}
a_{11}.b_{11} + a_{12}.b_{21}  &  a_{11}.b_{12} + a_{12}.b_{22} \\
a_{21}.b_{11} + a_{22}.b_{21}  &  a_{21}.b_{12} + a_{22}.b_{22} \\
a_{31}.b_{11} + a_{32}.b_{21}  &  a_{31}.b_{12} + a_{32}.b_{22}  \nonumber \\
\end{bmatrix}
=
\begin{bmatrix}
		c_{11} &  c_{12} \\
        c_{21} &  c_{22} \\
		c_{31} &  c_{32}  \nonumber \\
	\end{bmatrix}
\end{equation}




**Exercício :** Cálcule a multiplicação das matrizes abaixo usando método algébrico e compare com o resultado usando a biblioteca Numpy.

\begin{equation}
	A =
	\begin{bmatrix}
		1 &  2  \\
		3 &  4 \\
        5 &  6  \nonumber \\
        \end{bmatrix}_{(3x2)}
    \
    \
    \
    B =
	\begin{bmatrix}
		1 &  3 \\
		2 &  4  \nonumber \\
	\end{bmatrix}_{(2x2)}
\end{equation}


**Resultado:**

\begin{equation}
	C= A.B =
	\begin{bmatrix}
		5 & 11  \\
		11 & 25  \\
        17 & 39 \nonumber \\
        \end{bmatrix}
    \end{equation}



In [ ]:
# Cálculo usando métodos algébricos;

#Matriz A

a11, a12 = 1,2
a21, a22 = 3,4
a31, a32= 5,6

#Matriz B

b11, b12= 1,3
b21, b22= 2,4

# Matriz C = A.B
c11= a11*b11 + a12*b21
c12= a11*b12 + a12*b22
c21= a21*b11 + a22*b21
c22= a21*b12 + a22*b22
c31= a31*b11 + a32*b21
c32= a31*b12 + a32*b22

C = [[c11, c12],
     [c21, c22],
     [c31, c32]]

print(C)




[[5, 11], [11, 25], [17, 39]]


In [ ]:
# Utilizando a biblioteca numpy

A3 = np.array([[1,2],
                [3,4],
                [5,6]])

B3 = np.array ([[1,3],
                [2,4]])

C5 = np.matmul(A3,B3)

C5

array([[ 5, 11],
       [11, 25],
       [17, 39]])

#### Vamos resolver mais um exercício

Sabendo-se que a matriz $A$ e $B$ são dadas abaixo, calcule a matriz $C=A.B$.

\begin{equation}
	 	A =
 	\begin{bmatrix}
		2 & 3 \\
 		4 & 6 \\
 	\end{bmatrix}_{(2x2)}
 	\
 	\
 	B =
	\begin{bmatrix}
 		1 & 3 & 0 \\
		2 & 1 & 1 \\
	\end{bmatrix}_{(2x3)}
\end{equation}
……………………………..
#### Solução:
**Solução**:
 Vamos colocar as matrizes $A$ e $B$ com notações tais que: $A=[a_{i,j}]$ e $B=[b_{i,j}]$.

\begin{equation}
	 	\begin{bmatrix}
		 		a_{11} & a_{12} \\
		 		a_{21} & a_{22}
		 	\end{bmatrix}  
	 	.
	 	\begin{bmatrix}
		 		b_{11} & b_{12} & b_{13} \\
		 		b_{21} & b_{22} & b_{23}
		 	\end{bmatrix}
	 	=
	 	\begin{bmatrix}
a_{11}.b_{11} + a_{12}.b_{21} & a_{11}.b_{12} + a_{12}.b_{22}  & a_{11}.b_{13} + a_{12}.b_{23} \\
a_{21}.b_{11} + a_{22}.b_{21} & a_{21}.b_{12} + a_{22} b_{22} & a_{21}.b_{13} + a_{22}.b_{23}
		 \end{bmatrix}  
\end{equation}


In [ ]:
#Resolução em forma algébrica

#Matriz A

a11, a12 = 2,3
a21, a22 = 4,6

#Matriz B

b11, b12, b13 = 1,3,0
b21, b22,b23 = 2,1,1

#Matriz C

c11= a11*b11 + a12*b21
c12 = a11*b12 + a12*b22
c13 = a11*b13 + a12*b23
c21= a21*b11 + a22*b21
c22 = a21*b12 + a22*b22
c23 = a21*b13 + a22*b23

C = [[c11, c12, c13],
     [c21, c22, c23]]

print(C)



[[8, 9, 3], [16, 18, 6]]


In [ ]:
# Resolução por numpy

import numpy as np

A = np.array([[2,3],
              [4,6]])

B = np.array([[1,3,0],
              [2,1,1]])

C= np.matmul(A,B)

print(C)


[[ 8  9  3]
 [16 18  6]]


#### Exercício: Vamos resolver mais um exercício aumentando o número de colunas da matriz $B$.

Seja o conjunto de matrizes abaixo:

\begin{equation}
	A =
	\begin{bmatrix}
		a_{11} &  a_{12}  \\
		a_{21} &  a_{22} \\
        a_{31} &  a_{32}\nonumber \\
        \end{bmatrix}_{(3x2)}
    \
    \
    B =
	\begin{bmatrix}
		b_{11} &  b_{12} &  b_{13}  \\
		b_{21} &  b_{22} &  b_{23}  \nonumber \\
	\end{bmatrix}_{(2x3)}
\end{equation}

Como podemos fazer a multiplicação dessas matrizes?

\begin{equation}
C = A.B =
\begin{bmatrix}
a_{11}.b_{11} + a_{12}.b_{21}  &  a_{11}.b_{12} + a_{12}.b_{22} &  a_{11}.b_{13} + a_{12}.b_{23} \\
a_{21}.b_{11} + a_{22}.b_{21}  &  a_{21}.b_{12} + a_{22}.b_{22} &  a_{21}.b_{13} + a_{22}.b_{23} \\
b_{31}.b_{11} + a_{32}.b_{21}  &  a_{31}.b_{12} + a_{32}.b_{22} &  a_{31}.b_{13} + a_{32}.b_{23}   \nonumber \\
\end{bmatrix}
\end{equation}


#### Exercício de aplicação:

Vamos resolver de forma computacional a multiplicação das matrizes abaixo:

\begin{equation}
	A =
	\begin{bmatrix}
		1 & 2 \\
		3 & 4 \\
        5 & 6\nonumber \\
        \end{bmatrix}_{(3,2)}
    \
    \
    B =
	\begin{bmatrix}
		1 &  3 &  5  \\
		2 &  4 &  6  \nonumber \\
	\end{bmatrix}_{(2,3)}
\end{equation}

**Resposta :**
\begin{equation}
	A =
	\begin{bmatrix}
		5 & 11 & 17 \\
		11 & 25 & 39 \\
        17 & 39 & 61 \nonumber \\
        \end{bmatrix}
    \end{equation}


In [ ]:
#Resolução em forma algébrica

#Matriz A

a11, a12 = 1,2
a21, a22 = 3,4
a31, a32 = 5,6

#Matriz B

b11, b12, b13 = 1,3,5
b21, b22,b23 = 2,4,6

#Matriz C

c11= a11*b11 + a12*b21
c12 = a11*b12 + a12*b22
c13 = a11*b13 + a12*b23
c21= a21*b11 + a22*b21
c22 = a21*b12 + a22*b22
c23 = a21*b13 + a22*b23
c31 = a31*b11 + a32*b21
c32 = a31*b12 + a32*b22
c33 = a31*b13 + a32*b23


C = [[c11, c12, c13],
     [c21, c22, c23],
     [c31,c32,c33]]

print(C)


[[5, 11, 17], [11, 25, 39], [17, 39, 61]]


In [ ]:
#Resolução pela biblioteca do python

A = np.array([[1,2],
              [3,4],
              [5,6]])

B = np.array([[1,3,5],
              [2,4,6]])

C= np.matmul(A,B)

print(C)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
